define('text!extensions/framework/elements/core/menu/menu.html', [], function() {
    return '<div class="menu-container"><div class="oj-flex oj-flex-items-pad welcome-box"><!-- ko if:$properties.rootModel.isUserDataSet() --><div class="oj-flex-item oj-sm-12 welcome-box-item"><div><div data-bind="text : nls.welcomeNew" style="text-align:center;color:#fff;padding-bottom:5px"></div></div><div class="welcome-box-item__name" data-bind="text : $properties.baseModel.format(nls.welcome,{firstName : $properties.dashboard.userData.userProfile.firstName, lastName : $properties.dashboard.userData.userProfile.lastName})" style="text-align:center;font-weight:700;color:#fff;padding-bottom:5px"></div><div class="welcome-box-item__info" data-bind="text : $properties.baseModel.format(nls.lastLogin,{lastLoginDate : $properties.formatter.formatDate($properties.dashboard.userData.userProfile.preLastLoggedInDateTime, \'dateTimeFormat\')})" style="text-align:center;color:#fff;padding-bottom:2px"></div></div><!-- /ko --><!-- ko if: !$properties.baseModel.large() --><!-- /ko --><!-- ko if: menuDrillMode() === "sliding" --><oj-button display="icons" chroming="half" on-click=\'[[changeMenuState.bind(null,"toggle")]]\' class="oj-panel-remove-button"><span slot="endIcon" class="oj-panel-remove-icon"></span></oj-button><!-- /ko --></div><oj-navigation-list id="dummyNav" root-label="[[nls.rootLabel]]" tabindex="-1" class="mobileMenu" selection="{{selectedItem}}" drill-mode="[[menuDrillMode()]]" on-selection-changed="[[optionChange]]" item.selectable=" {{itemOnly}}" data-oj-context><ul data-bind="template: {name: \'menuTemplate\', foreach: listItem, as: \'item\'}"></ul><script type="text/html" id="menuTemplate"><li data-bind="attr: {id: $properties.baseModel.incrementIdCount()}"><a href="#" data-bind="attr:{\'alt\':$parents[$parents.length-1].nls.menu.groups[name]}"><!-- ko if:$data.icon--> <span class="oj-navigationlist-item-icon icons" data-bind="css:$data.icon"></span><!-- /ko --><!-- ko text: $parents[$parents.length-1].nls.menu.groups[name] --><!-- /ko --> </a><!-- ko if: item.submenus --><ul data-bind="template: {name: \'menuTemplate\', foreach: item.submenus, as: \'item\', data : {name1 : $data.name}}"></ul><!-- /ko --></li></script></oj-navigation-list></div>';
});

define('resources/nls/menu', [], function() {
    "use strict";
    return new function() {
        return {
            root: {
                menu: {
                    mailboxAlt: "Mail Box",
                    mailbox: "Mail Box",
                    groups: {
                        "loan-drawdown": "Loan Drawdown Request",
                        "sweep-in-instruction": "Manage Sweep-in",
                        certificates: "Certificates",
                        "interest-certificates": "Interest Certificates",
                        "balance-certificate": "Balance Certificates",
                        "interest-certificate-casa": "Current and Savings",
                        "interest-certificate-td": "Deposits",
                        "interest-certificate-loans": "Loans",
                        "tax-deduction-at-source": "TDS",
                        "compliance-base": "Compliance",
                        "entity-compliance-base": "Entity Compliance",
                        DASHBOARD: "Dashboard",
                        ACCOUNTS_TITLE: "Accounts",
                        RECURRING_DEPOSIT_TITLE: "Recurring Deposits",
                        "rd-details": "Recurring Deposit Details",
                        "rd-redeem": "Redemption",
                        "rd-calculator": "New Recurring Deposit",
                        "rd-amend": "Edit Maturity Instruction",
                        "view-statement": "View Statement",
                        redemption: "Redemption",
                        "request-statement": "Request Statement",
                        SETUP: "Setups",
                        INQUIRES: "Inquiries",
                        PAYMENTS_TITLE: "Transactions",
                        "task-purpose-landing": "Payment Purpose Mapping",
                        "segment-payee-restriction-mapping": "Payee Restriction",
                        "manage-category": "Biller Category Maintenance",
                        "view-forex-deal-settings": "Forex Deal Settings",
                        "biller-category-landing": "Biller Category Maintenance - Integrated",
                        "view-network-preference": "Network Preference Maintenance",
                        "hard-token-synchronization-and-unlock": "Activate Security Token",
                        "send-to-other-enaira": "Send to other eNaira",
                        E_NAIRA_WALLET: "eNaira Wallet",
                        "transfer-to-ecobank-within-africa": "Ecobank Africa",
                        "transfer-to-ecobank-within-africa2": "Ecobank Africa",
                        "rt-receivemoney": "Rapid Transfer Receive",
                        "rt-history": "Rapid Transfer History",
                        CASA_ACCOUNT_TITLE: "My Accounts",
                        CASA_ACCOUNT: "My Accounts",
                        "casa-nominee-list": "Current and Savings",
                        "td-nominee-list": "Term Deposits",
                        "rd-nominee-list": "Recurring Deposits",
                        "apply-online": "Apply Online",
                        redirection: "Product Offerings",
                        "application-tracking-base": "Track your Application",
                        "application-mobile-tracker": "Track your Application",
                        "personalize-your-bundle": "Make your own bundle",
                        nominee: "Nominee",
                        "demand-deposits": "Overview",
                        "demand-deposit-transactions": "View Statement",
                        "account-transactions": "View Statement",
                        "term-deposit-transactions": "View Statement",
                        "recurring-deposit-transactions": "View Statement",
                        "loan-transactions": "View Statement",
                        "cheque-status-inquiry": "Cheque Status Inquiry",
                        "cheque-book-request": "Cheque Book Request",
                        "cheque-stop-unblock": "Stop/Unblock Cheque",
                        "statement-request": "Request Statement",
                        "debit-card-list": "Debit Cards",
                        TERM_DEPOSIT_ACCOUNT: "Term Deposits",
                        "term-deposits": "Overview",
                        "td-details": "Term Deposit Details",
                        "demand-deposit-details": "Account Details",
                        "td-topup": "Top Up",
                        "td-open": "New Deposit",
                        "td-redeem": "Redemption",
                        "td-amend": "Edit Maturity Instruction",
                        UPI: "UPI",
                        "manage-vpa": "Manage VPA",
                        "upi-request-money": "Request Money",
                        "upi-pending-request": "Pending Requests",
                        "split-money-list": "Split Bill",
                        "transaction-history": "Transaction History",
                        "adhoc-transfer-vpa": "Adhoc Transfer",
                        "transfer-payee-upi": "Transfer To Beneficiaries",
                        "view-forex-deal": "Forex Deal",
                        LIQUIDITY_MANAGEMENT_TITLE: "Liquidity Management",
                        "liquidity-management": "Overview",
                        "create-structure": "Create Structure",
                        "log-monitors": "Log Monitors",
                        "list-structure": "Structure List",
                        LOAN: "Loans and Finances",
                        loans: "Overview",
                        "loan-details": "Loan Details",
                        "retail-loan-details": "Loan Details",
                        "loan-repayment": "Loan and Finance Repayment",
                        "loan-disbursement": "Disbursement Inquiry",
                        "loan-schedule": "Schedule Inquiry",
                        AGGREGATE_ACCOUNT: "Aggregate Accounts",
                        aggreate_accounts_list: "Register Account",
                        NOMINATIONS_TITLE: "Nominations",
                        TRADE_FINANCE: "Trade Finance",
                        "trade-finance": "Overview",
                        "shipping-guarantee-nav-bar": "Initiate Shipping Guarantee",
                        "collection-nav-bar": "Initiate Export Collection",
                        "collection-navigation": "Initiate Export Collection",
                        "guarantee-nav-bar": "Initiate Bank Guarantee",
                        "guarantee-navigation": "Initiate Bank Guarantee",
                        "shipping-guarantees": "View Shipping Guarantee",
                        "shipping-guarantee": "Shipping Guarantee",
                        "shipping-guarantee-list": "View Shipping Guarantee",
                        "letter-of-credit": "Letter Of Credit",
                        "import-letter-of-credit": "Import Letter of Credit",
                        "export-letter-of-credit": "Export Letter of Credit",
                        "lc-nav-bar": "Initiate Letter of Credit",
                        "initiate-import-lc-amend": "Amend Letter of Credit",
                        "initiate-outward-guarantee-amend": "Amend Bank Guarantee",
                        "amend-guarantee-list": "Amend Bank Guarantee",
                        "import-lc": "View Letter of Credit",
                        "export-lc": "View Letter of Credit",
                        "view-import-lc": "View Letter of Credit",
                        "view-export-lc": "View Letter of Credit",
                        discrepancies: "Bill Discrepancy Acceptance",
                        "bill-discrepancies": "Bill Discrepancy Acceptance",
                        "initiate-customer-acceptance": "LC Amendment Acceptance",
                        "inward-guarantee-amendment": "Guarantee Amendment Acceptance",
                        bills: "Bills",
                        "import-bills": "View Bill",
                        "export-bills": "View Bill",
                        "other-party-navigation": "Other Party Maintenance",
                        Maintenance: "Maintenance",
                        "view-import-bill": "View Bill",
                        "view-export-bill": "View Bill",
                        "list-collection": "Initiate Export Collection",
                        "bill-settlement": "Settlement of Bill",
                        collection: "Collection",
                        "list-bills": "Initiate Bills",
                        "bills-navigation": "Initiate Bills",
                        "import-collection-submenu": "Import Collection",
                        "export-collection-submenu": "Export Collection",
                        "import-collection": "View Import Collection",
                        "export-collection": "View Export Collection",
                        "view-import-collection": "View Import Collection",
                        "view-export-collection": "View Export Collection",
                        guarantee: "Bank Guarantee",
                        "inward-bank-guarantee": "Inward Bank Guarantee",
                        "outward-bank-guarantee": "Outward Bank Guarantee",
                        "guarantee-list": "Initiate Bank Guarantee",
                        "outward-guarantees": "View Bank Guarantee",
                        "outward-guarantee-list": "View Bank Guarantee",
                        "inward-guarantee-list": "View Bank Guarantee",
                        "inward-guarantees": "View Bank Guarantee",
                        "customer-acceptance-nav-bar": "Customer Acceptance",
                        "customer-acceptance-lc-base": "LC Amendments",
                        "customer-acceptance-bills-base": "Bill Discrepancies",
                        "customer-acceptance-guarantee-base": "Guarantee Amendments",
                        "search-beneficiary-maintenance": "Beneficiary Maintenance",
                        "search-credit-line": "Line Limits Utilization",
                        PAYMENTS_OVERVIEW: "Overview",
                        "payee-list": "Manage Beneficiaries",
                        "bene-user-mapping": "Beneficiary User Mapping",
                        "biller-list": "Manage Billers",
                        "payments-payee-list": "Manage Beneficiaries",
                        "standing-instructions-list": "Standing Order",
                        "standing-instructions-landing": "Standing Order",
                        "bill-payments": "Pay Bills",
                        "payments-money-transfer": "Other Transfers",
                        "international-low-value-payment": "International Low Value Payment",
                        "generic-money-transfer": "Transfer To Saved Beneficiary",
                        "payments-transfers": "Payments and Transfers",
                        "adhoc-payments": "One Time Transfer",
                        "adhoc-payments-generic": "One Time Transfer",
                        "multiple-transfers": "Multiple Transfers",
                        "multiple-payments": "Multiple Transfers",
                        "mt101-instruction": "MT101 Instruction",
                        "mt101-instructions-inquiry": "MT101 Instructions Inquiry",
                        "multiple-bill-payments": "Multiple Bill Payments",
                        "adhoc-demand-draft": "Demand Draft",
                        "issue-demand-draft": "Issue Demand Drafts",
                        "debtor-money-request": "Request Money",
                        "debtor-group-list": "Manage Debtors",
                        "scheduled-payments": "Upcoming Payment",
                        "inward-remittance-inquiry": "Inward Remittance Inquiry",
                        "requested-funds-summary": "Requested Funds Summary",
                        "add-money-to-wallet": "Add Money To Wallet",
                        "payment-status-inquiry-corp": "Payment Status Inquiry",
                        "payment-status-inquiry": "Transaction Status Inquiry",
                        favorites: "Favorites",
                        CREDIT_CARD_TITLE: "Credit Cards",
                        CC_OVERVIEW: "Overview",
                        "card-details": "Credit Card Details",
                        "card-statement": "View Statement",
                        "card-pay": "Card Payment",
                        "request-pin": "Request PIN",
                        "block-card": "Block/Cancel Card",
                        "auto-pay": "Auto Pay",
                        "creditcard-reset-pin": "Reset PIN",
                        "add-on-card": "Add-On Card",
                        MAILBOX_TITLE: "Mail Box",
                        PERSONAL_FINANCE_MANAGEMENT: "Personal Financial Management",
                        "spend-category-landing": "Spend Category Maintenance",
                        "goal-category-list": "Goal Category Maintenance",
                        "add-ext-bank": "External Bank Maintenance",
                        "list-budget": "Budget",
                        "list-goal": "Goal List",
                        "goal-category-selection": "New Goal",
                        GOAL: "Goal",
                        SPEND: "Spend",
                        "manage-spend-categories": "Manage Categories",
                        "transaction-list": "View Transactions",
                        "mailbox-base": "Email",
                        "alert-list": "Alerts",
                        "notification-list": "Notifications",
                        FILE_UPLOAD: "Bulk File Upload",
                        ACCESS_POLICIES: "Authorization and Access Controls",
                        "access-point-search": "Touch Points",
                        "access-point-group-search": "Touch Points Group",
                        "application-role-base": "Role Transaction Mapping",
                        "entitlements-base": "Entitlements",
                        "search-segments": "User Segments Definition",
                        "file-identifier-search": "File Identifier Maintenance",
                        "user-search": "User File Identifier Mapping",
                        "file-create": "File Identifier Maintenance",
                        "user-search-type": "User File Identifier Mapping",
                        "file-upload": "Bulk File Upload",
                        "file-view": "Uploaded Files Inquiry",
                        "file-view-fu": "Uploaded Files Inquiry",
                        "setup-expected-cashflow-landing": "Create Expected Cash Flow",
                        "view-payments": "View Payments",
                        VIRTUAL_ACCOUNT_MANAGEMENT_TITLE: "Virtual Account Management",
                        "virtual-account-management": "Overview",
                        "virtual-entity": "Virtual Entity",
                        "virtual-entity-landing": "Virtual Entity",
                        "virtual-account-landing": "Virtual Accounts",
                        "virtual-account-main": "Virtual Account",
                        "virtual-account-closure": "Close Virtual Account",
                        "virtual-entity-search": "View/Edit Virtual Entity",
                        "virtual-entity-create": "Create Virtual Entity",
                        "virtual-account-search": "View/Edit Virtual Account",
                        "virtual-account-creation-landing": "Create Virtual Account",
                        "virtual-account-closure-listing": "Initiate Closure",
                        "virtual-account-track-closure": "Track Closure",
                        "virtual-structure-search": "View/Edit Structure",
                        "virtual-structure": "Virtual Accounts Structure",
                        "virtual-account-structure-creation-landing": "Create Structure",
                        "virtual-multi-currency-account-main": "Virtual Multi-Currency Account",
                        "virtual-multi-currency-account": "Create Virtual Multi-Currency Account",
                        "virtual-multi-currency-account-search": "View/Edit Virtual Multi-Currency Account",
                        "create-move-money": "Move Money",
                        "virtual-account-statement": "Transaction Inquiry",
                        "internal-credit-line": "Internal Credit Line",
                        "create-internal-credit-line": "Create Internal Credit Line",
                        "internal-credit-line-search": "View/Edit Internal Credit Line",
                        "credit-line-linkage": "Link Internal Credit Line",
                        "general-rate-maintenance-search": "View/Edit General Rates",
                        "general-rate-maintenance": "Add General Rates",
                        "special-rate-maintenance-search": "View/Edit Special Rates",
                        "special-rate-maintenance": "Add Special Rates",
                        "vam-reports": "Pre-Generated Statement",
                        "vam-adhoc-reports": "Adhoc Statement",
                        "rate-maintenance": "Interest Rate",
                        "reports-statement": "Statements",
                        PARTY_TO_PARTY_LINKAGE: "Party To Party Linkage",
                        ON_BOARDING: "Onboarding",
                        "biller-search": "Biller Onboarding",
                        COMMUNICATION: "Communication",
                        "mapping-base": "User Group Subject Mapping",
                        "mailers-base": "Mailers",
                        CONTROLS_AND_MONITORING: "Controls and Monitoring",
                        USER_EXPERIENCE: "User Experience",
                        TEMPLATES: "Templates",
                        CONFIGURATION: "Configuration",
                        "system-configuration-home": "System Configuration",
                        "system-rules-map": "System Rules",
                        "task-aspects": "Transaction Aspects",
                        "location-search": "ATM/Branch Maintenance",
                        "user-segments-product-list": "Product Mapping",
                        "profile-maintenance-search": "User Profile Maintenance",
                        OAUTH: "OAuth",
                        "resource-server-search": "Resource Server Maintenance",
                        "identity-domain-search": "Identity Domain Maintenance",
                        "client-search": "Client Maintenance",
                        "client-search-extension": "eIDAS Client Attributes",
                        USER_MANAGEMENT: "User Management",
                        CORPORATE_PREFERENCES: "Party Preferences",
                        LIMITS: "Limits",
                        "limit-search": "Limit Definition",
                        "limit-package-search": "Limits Package",
                        "transaction-group-search": "Transaction Group Maintenance",
                        APPROVALS: "Approvals",
                        "workflow-type": "Workflow Management",
                        "rule-type": "Rules Management",
                        workflow: "Workflow Management",
                        rules: "Rules Management",
                        "user-group-type": "User Group Management",
                        ACCESS_MANAGEMENT: "Access Management",
                        ACCOUNT_ACCESS: "Account Access",
                        RESOURCE_ACCESS: "Resource Access",
                        "access-management-base": "Party Account Access",
                        "party-base": "Party Resource Access",
                        "user-base": "User Resource Access",
                        SERVICE_REQUEST_CONFIG: "Service Requests",
                        "service-requests-menu": "More Services",
                        "service-requests-track": "Track Request",
                        "service-requests-base": "Request Processing",
                        "dashboard-create": "Personalize Dashboard",
                        "view-dashboard-design": "Personalize Dashboard",
                        "feedback-capture": "Leave Feedback",
                        "feedback-template-search": "Feedback Template",
                        "sms-banking-search": "SMS and Missed Call Banking",
                        "service-requests-base-main": "Raise New Request",
                        "user-access-management-base": "User Account Access",
                        "manage-service-request": "Manage Service Requests",
                        SUPPLY_CHAIN_FINANCE: "Supply Chain Finance",
                        PROGRAM_MANAGEMENT: "Program Management",
                        "supply-chain-finance": "Overview",
                        "program-management-global": "Create Program",
                        "invoice-accept-reject": "Accept/Reject Invoice",
                        "link-invoices-to-program": "Link Invoice to Program",
                        "select-role": "View/Edit Program",
                        "view-limits": "View Limits",
                        INVOICE_MANAGEMENT: "Invoice Management",
                        "invoice-creation-home": "Create Invoice",
                        "select-role-invoice": "View/Edit Invoice",
                        "invoice-creation-landing": "Create Invoice",
                        "select-invoice-role": "View/Edit Invoice",
                        "invoice-status-update": "Accept/Reject Invoice",
                        ASSOCIATED_PARTY_MANAGEMENT: "Associated Party Management",
                        "onboard-associated-party": "Onboard Associated Party",
                        "counter-party-list": "View Associated Parties",
                        "view-associated-parties": "View Associated Parties",
                        FINANCE_MANAGEMENT: "Finance Management",
                        "request-finance": "Request Finance",
                        "view-finances": "View Finances",
                        "repay-finance-form": "Finance Repayment",
                        CASH_MANAGEMENT: "Cash Management",
                        reconciliation: "Reconciliation",
                        "reconciliation-overview": "Overview",
                        "purchase-order-management-overview": "Overview",
                        RECEIVABLES_MANAGEMENT: "Receivables Management",
                        PURCHASE_ORDER_MANAGEMENT: "Purchase Order Management",
                        "purchase-order-landing": "Purchase Order Creation",
                        "select-purchase-order-role": "View Purchase Orders",
                        "purchase-order-status-update": "Accept/Reject Purchase Order",
                        "set-up-reconciliation-rules": "Create Reconciliation Rule",
                        "set-up-allocation-rules": "Create Allocation Rule",
                        MANUAL_RECONCILIATION: "Manual Reconciliation",
                        "manual-invoice-reconciliation": "Invoice against Payment",
                        "manual-cash-flow-reconciliation": "Cash Flow against Payment",
                        "cashflow-delete-reconciliation": "Cash Flow - Payment",
                        "manual-allocation": "Manual Allocation",
                        MANUAL_DERECONCILIATION: "De-Reconciliation",
                        "manual-delete-reconciliation": "Invoice - Payment",
                        "view-reconciliation-rules": "View/Edit Reconciliation Rule",
                        "cash-flow": "Cash Flow",
                        "cash-flow-forecasting-summary": "Cash Flow Forecasting",
                        "cash-flow-transaction-inquiry": "View/Edit Expected Cash Flow Details",
                        WEALTH_MANAGEMENT: "Wealth Management",
                        "mutual-funds": "Overview",
                        START_INVESTING: "Start Investing",
                        PLACE_ORDERS: "Place Orders",
                        REPORTS: "Reports",
                        "purchase-mutual-fund-train": "Purchase Mutual Fund",
                        "risk-profile-account-selection": "Risk Profiling",
                        "redeem-funds-global": "Redeem Mutual Fund",
                        "order-status": "Order Status",
                        "capital-gain-reports": "Capital Gains Report",
                        "dividend-reports": "Dividends Report",
                        "transaction-reports": "Transactions Report",
                        "switch-funds-global": "Switch Mutual Fund",
                        "investment-details-dashboard": "Investment Details",
                        "open-investment-account-landing": "Open Investment Account",
                        "report-generation": "Report Generation",
                        "report-list": "My Reports",
                        "reports-type": "User Report Mapping",
                        "audit-log": "Audit Log",
                        OTHERS: "Others",
                        "transaction-cutoff": "Working Window",
                        "help-desk-user-search": "User Help Desk",
                        "application-message-list": "Message Maintenance",
                        SECURITY: "Security",
                        "segment-authentication-mapping": "Authentication",
                        "view-security-question-maintenance": "Manage Security Questions",
                        "policy-search": "Password Policy Maintenance",
                        "alerts-maintenance-search": "Alert Maintenance",
                        "manage-alerts-subscription": "Manage Alerts",
                        "alerts-select-user": "Alert Subscription",
                        "claim-payment-dashboard": "Claim Money",
                        "clarification-details": "Clarification",
                        "track-application": "Track Application",
                        "user-credentials": "Register",
                        "service-requests-search": "Service Request-Form Builder",
                        "security-keys": "Security Keys",
                        origination: "Workflow Configuration",
                        login: "Login",
                        logout: "Logout",
                        clickhere: "Click to view {name}",
                        locator: "ATM/Branch Locator",
                        "preference-base": "Party Preferences",
                        users: "User Management",
                        "linkage-base": "Party To Party Linkage",
                        profile: "My Profile",
                        "template-list": "Dashboard Builder",
                        "theme-list": "Manage Brand",
                        ACCOUNT_SETTING: "Account Setting",
                        "session-summary": "Session Summary",
                        "alerts-list": "Manage Alerts",
                        "list-user": "User Limits",
                        "my-limit": "Transaction Limit",
                        "view-user-security-question": "Set Security Question",
                        "change-password": "Change Password",
                        "revoke-tpp-access": "Revoke Third Party Provider Access",
                        "manage-tpp-list": "Manage Third Party Provider List",
                        "print-user-search": "Print Password",
                        "security-menu": "Set Security Questions",
                        help: "Help",
                        about: "About",
                        "oracle-live": "OLive Help!",
                        "third-party-consents": "Manage Third Party Consents",
                        "feedback-analysis": "Feedback Analytics",
                        BILL_PAYMENTS_TITLE: "Bill Payments",
                        API_BUILDER: "API Builder",
                        "api-group-search": "Group Builder",
                        "api-builder-search": "Service Builder",
                        "bill-payments-favorites": "Favorites",
                        "modify-biller": "Manage Billers",
                        "quick-bill-payment": "Quick Bill Pay",
                        "quick-recharge": "Quick Recharge",
                        "payment-history": "Bill Payment History",
                        "side-menu": "View Profile",
                        "manage-bill-payments": "Manage Airtime Beneficiaries",
                        "paybill-beneficiary": "Manage Paybill Beneficiaries",
                        "air-time": "Buy Airtime",
                        tax: "Pay Tax",
                        "mobile-money": "Mobile Money",
                        "data-bundle": "Buy Data",
                        ACCOUNT_SETTINGS: "Account Settings",
                        TPP_ACCESS: "Third Party Access",
                        trends: "Trends",
                        "link-account-dashboard": "EcobankMax",
                        "merchant-dashboard": "Merchant Management",
                        "facility-collateral-management": "Credit Facility Management",
                        "credit-facility": "Overview",
                        "credit-facility-title": "Credit Facility",
                        "facility-overview": "Facility Summary",
                        "facility-details": "Facility Details",
                        "choose-facility-option": "Amend Facility",
                        "choose-sub-facility-option": "Apply for Sub Facility",
                        "apply-new-facility-landing": "Apply for New Facility",
                        collaterals: "Collaterals",
                        "relationship-mapping-base": "Relationship Mapping",
                        "relationship-matrix-base": "Relationship Matrix",
                        "transaction-blackout": "Transaction Blackout",
                        "collateral-overview": "Collateral Summary",
                        "collateral-details": "Collateral Details",
                        "collateral-evaluation-landing": "Collateral Evaluation",
                        "collateral-revaluation-flow": "Collateral Revaluation",
                        "workflow-configuration-search": "Origination Workflow Configuration",
                        "application-tracker-film-strip": "Application Tracker",
                        "additional-conditions-maintenance-create": "Additional Conditions Maintenance",
                        "initiate-clause-maintenance": "Clause Maintenance",
                        "lodge-claims": "Lodge Claim",
                        "add-link-wallet": "Add/Link eWallet",
                        "wallet-login-screen": "Check Balance",
                        "send-to-your-enaira-login": "Send to your eNaira",
                        "rapid-transfer-send": "Rapid Transfer Send",
                        "domestic-transfer-nigeria": "Domestic Transfer Nigeria",
                        "domestic-transfer-ghana": "Domestic Transfer Ghana",
                        "hard-token-mapping": "Token Mapping",
                        Rapid_Transfer: "Rapid Transfer",
                        Transactions_Title: "Transactions",
                        More_Services: "More Services",
                        Manage_billers: "Manage billers",
                        Once_off_bill_payment: "Pay Bill",
                        "adhoc-payments-corp": "One Time Payment",
                        "INQUIRES-corp": "Payment Inquiries",
                        "add-biller": "Add Biller",
                        Remmittence_Benificiaries: "Remittance",
                        Other: "Other",
                        Requests: "Requests",
                        Location: "Location",
                        Security: "Security Settings",
                        Notification: "Notifications",
                        "workflow-base": "Product Configuration"
                    }
                },
                welcomeNew: "Welcome ,",
                welcome: "{firstName} {lastName}",
                lastLogin: "Last login {lastLoginDate}",
                changeLanguage: "Click to change current language",
                selectLanguage: "Select Language",
                rootLabel: "Menu"
            },
            ar: !0,
            es: !0,
            pt: !0,
            fr: !0,
            zh_CN: !0,
            cs: !0,
            sv: !0,
            en: !1,
            "en-us": !1,
            el: !0
        }
    }
});

define('extensions/framework/elements/core/menu/menu', ["ojs/ojcore", "knockout", "ojL10n!resources/nls/menu", "platform", "framework/js/constants/constants", "ojs/ojnavigationlist", "ojs/ojselectcombobox", "ojs/ojjquery-hammer", "ojs/ojjsontreedatasource", "framework/elements/core/entity-switch/loader"], function(e, r, o, t, s) {
    "use strict";
    return function(a) {
        const n = this;
        n.languageOptions = a.properties.languageOptions, n.changeMenuState = a.properties.changeMenuState, a.properties.baseModel.registerElement("breadcrumb", "core"), a.properties.baseModel.registerComponent("profile", "base-components"), a.properties.baseModel.registerElement("about", "core"), a.properties.baseModel.registerComponent("mailbox-base", "mailbox"), a.properties.baseModel.registerComponent("alert-list", "mailbox"), a.properties.baseModel.registerComponent("notification-list", "mailbox"), n.showSecuritySettings = r.observable(!1), n.selectedItem = r.observable("").extend({
            notify: "always"
        }), n.menuDrillMode = r.observable("sliding"), n.listItem = r.observableArray(), n.nls = o, n.optionChange = function(e) {
            e.detail.item && (a.properties.baseModel.closeNotificationMessages(), a.properties.dashboard.headerCaption(""), a.properties.menuOptionSelect(r.dataFor(e.detail.item), n.changeMenuState("toggle")))
        }, n.selectedItem.subscribe(function(e) {
            e && n.selectedItem(null)
        }), a.properties.baseModel.addEvent("open-menu", {
            element: document,
            eventName: "keyup",
            eventHandler: function(e) {
                77 === e.keyCode && e.altKey && (e.preventDefault(), n.changeMenuState("toggle"))
            }
        }), a.properties.baseModel.addEvent("menuReload", {
            element: window,
            eventName: "menuChanged",
            eventHandler: function() {
                const r = s.jsonContext ? s.jsonContext : "framework/json";
                var o = null;
                o = a.properties.dashboard && a.properties.dashboard.userData && a.properties.dashboard.userData.userProfile && a.properties.dashboard.userData.userProfile.roles && null !== a.properties.dashboard.userData.userProfile.roles[1] && ("LimitsMaker" === a.properties.dashboard.userData.userProfile.roles[1] || "LimitsChecker" === a.properties.dashboard.userData.userProfile.roles[1] || "ViewOnly" === a.properties.dashboard.userData.userProfile.roles[1] || "ContactCenterMaker" === a.properties.dashboard.userData.userProfile.roles[1] || "ContactCenterChecker" === a.properties.dashboard.userData.userProfile.roles[1] || "RPCMaker" === a.properties.dashboard.userData.userProfile.roles[1] || "RPCChecker" === a.properties.dashboard.userData.userProfile.roles[1] || "FraudMonitoringMaker" === a.properties.dashboard.userData.userProfile.roles[1] || "FraudMonitoringChecker" === a.properties.dashboard.userData.userProfile.roles[1] || "BranchMaker" === a.properties.dashboard.userData.userProfile.roles[1] || "BranchChecker" === a.properties.dashboard.userData.userProfile.roles[1] || "HelpDesk" === a.properties.dashboard.userData.userProfile.roles[1] || "TSGMaker" === a.properties.dashboard.userData.userProfile.roles[1] || "TSGChecker" === a.properties.dashboard.userData.userProfile.roles[1] || "BranchViewer" === a.properties.dashboard.userData.userProfile.roles[1] || "InternationalTransferOperations" === a.properties.dashboard.userData.userProfile.roles[1]) ? a.properties.dashboard.userData.userProfile.roles[1] : a.properties.computeContext(a.properties.dashboard.appData.segment), "OBDX_BU" === s.currentEntity && "RETAIL" === s.userSegment && (o = "retailnigeria"), require(["load!" + r + "/menu/" + o + ".json"], function(r) {
                    if (a.properties.baseModel.large()) {
                        const e = r.filter(function(e) {
                            return "oracle-live" !== e.name
                        });
                        r = e
                    }
                    n.menuDrillMode(getComputedStyle(document.querySelector(":root")).getPropertyValue("--menu-interaction") || "sliding"), n.listItem(a.properties.filterMenu(r)),
                        function() {
                            const r = document.querySelector(".menu-container oj-navigation-list");
                            e.Context.getContext(r).getBusyContext().whenReady().then(function() {
                                r.refresh()
                            })
                        }()
                })
            }
        }), a.properties.rootModel.userInfoPromise.then(function(e) {
            a.properties.dashboard.appData = e.appData, a.properties.baseModel.dispatchCustomEvent(window, "menuChanged"), a.properties.dashboard.userData.userProfile && t.getInstance("device").then(function(e) {
                e("displaySecurity", a.properties.dashboard.userData.userProfile.userName, n.showSecuritySettings)
            })
        }), n.itemOnly = function(e) {
            return void 0 === e.leaf || e.leaf
        }
    }
});

define('text!extensions/framework/elements/core/menu/component.json', [], function() {
    return '{\r\n  "name": "obdx-menu",\r\n  "version": "1.0.0",\r\n  "jetVersion": "^8.1.0",\r\n  "displayName": "Framework Composite Component",\r\n  "description": "Framework Composite Component",\r\n  "properties": {\r\n    "rootModel": {\r\n      "description": "Root Model Object",\r\n      "type": "object"\r\n    },\r\n    "dashboard": {\r\n      "description": "Dashboard Object",\r\n      "type": "object",\r\n      "writeback": true\r\n    },\r\n    "baseModel": {\r\n      "description": "BaseModel Object",\r\n      "type": "object"\r\n    },\r\n    "formatter": {\r\n      "description": "Formatter Object",\r\n      "type": "object"\r\n    },\r\n    "computeContext": {\r\n      "description": "Compute Context Function",\r\n      "type": "function"\r\n    },\r\n    "menuOptionSelect": {\r\n      "description": "Menu Option Select Function",\r\n      "type": "function"\r\n    },\r\n    "changeMenuState": {\r\n      "description": "Change Menu State Function",\r\n      "type": "function"\r\n    },\r\n    "filterMenu": {\r\n      "description": "Filter Menu Function",\r\n      "type": "function"\r\n    }\r\n  },\r\n  "methods": {},\r\n  "events": {},\r\n  "slots": {}\r\n}';
});

define('extensions/framework/elements/core/menu/loader', ["ojs/ojcomposite", "text!./menu.html", "./menu", "text!./component.json"], function(e, t, o, n) {
    "use strict";
    e.register("obdx-menu", {
        view: t,
        viewModel: o,
        metadata: JSON.parse(n)
    })
});